-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2017.1
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity astroSim is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    result_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    result_ce0 : OUT STD_LOGIC;
    result_we0 : OUT STD_LOGIC;
    result_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    result_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
    result_ce1 : OUT STD_LOGIC;
    result_we1 : OUT STD_LOGIC;
    result_d1 : OUT STD_LOGIC_VECTOR (63 downto 0) );
end;


architecture behav of astroSim is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "astroSim,hls_ip_2017_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu19eg-ffve1924-3-e-es2,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=17.418000,HLS_SYN_LAT=534177,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=650,HLS_SYN_FF=100466,HLS_SYN_LUT=111714}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal grp_janus_run_fu_120_ap_start : STD_LOGIC;
    signal grp_janus_run_fu_120_ap_done : STD_LOGIC;
    signal grp_janus_run_fu_120_ap_idle : STD_LOGIC;
    signal grp_janus_run_fu_120_ap_ready : STD_LOGIC;
    signal grp_janus_run_fu_120_p_int_out_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_janus_run_fu_120_p_int_out_ce0 : STD_LOGIC;
    signal grp_janus_run_fu_120_p_int_out_we0 : STD_LOGIC;
    signal grp_janus_run_fu_120_p_int_out_d0 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_janus_run_fu_120_p_int_out_address1 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_janus_run_fu_120_p_int_out_ce1 : STD_LOGIC;
    signal grp_janus_run_fu_120_p_int_out_we1 : STD_LOGIC;
    signal grp_janus_run_fu_120_p_int_out_d1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_reg_grp_janus_run_fu_120_ap_start : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);

    component janus_run IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        p_int_out_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        p_int_out_ce0 : OUT STD_LOGIC;
        p_int_out_we0 : OUT STD_LOGIC;
        p_int_out_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
        p_int_out_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
        p_int_out_ce1 : OUT STD_LOGIC;
        p_int_out_we1 : OUT STD_LOGIC;
        p_int_out_d1 : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;



begin
    grp_janus_run_fu_120 : component janus_run
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_janus_run_fu_120_ap_start,
        ap_done => grp_janus_run_fu_120_ap_done,
        ap_idle => grp_janus_run_fu_120_ap_idle,
        ap_ready => grp_janus_run_fu_120_ap_ready,
        p_int_out_address0 => grp_janus_run_fu_120_p_int_out_address0,
        p_int_out_ce0 => grp_janus_run_fu_120_p_int_out_ce0,
        p_int_out_we0 => grp_janus_run_fu_120_p_int_out_we0,
        p_int_out_d0 => grp_janus_run_fu_120_p_int_out_d0,
        p_int_out_address1 => grp_janus_run_fu_120_p_int_out_address1,
        p_int_out_ce1 => grp_janus_run_fu_120_p_int_out_ce1,
        p_int_out_we1 => grp_janus_run_fu_120_p_int_out_we1,
        p_int_out_d1 => grp_janus_run_fu_120_p_int_out_d1);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_reg_grp_janus_run_fu_120_ap_start_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_grp_janus_run_fu_120_ap_start <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    ap_reg_grp_janus_run_fu_120_ap_start <= ap_const_logic_1;
                elsif ((ap_const_logic_1 = grp_janus_run_fu_120_ap_ready)) then 
                    ap_reg_grp_janus_run_fu_120_ap_start <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_janus_run_fu_120_ap_done, ap_CS_fsm_state2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_janus_run_fu_120_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);

    ap_done_assign_proc : process(grp_janus_run_fu_120_ap_done, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_janus_run_fu_120_ap_done = ap_const_logic_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_0 = ap_start) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_janus_run_fu_120_ap_done, ap_CS_fsm_state2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_janus_run_fu_120_ap_done = ap_const_logic_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_janus_run_fu_120_ap_start <= ap_reg_grp_janus_run_fu_120_ap_start;
    result_address0 <= grp_janus_run_fu_120_p_int_out_address0;
    result_address1 <= grp_janus_run_fu_120_p_int_out_address1;
    result_ce0 <= grp_janus_run_fu_120_p_int_out_ce0;
    result_ce1 <= grp_janus_run_fu_120_p_int_out_ce1;
    result_d0 <= grp_janus_run_fu_120_p_int_out_d0;
    result_d1 <= grp_janus_run_fu_120_p_int_out_d1;
    result_we0 <= grp_janus_run_fu_120_p_int_out_we0;
    result_we1 <= grp_janus_run_fu_120_p_int_out_we1;
end behav;
